version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      all:
        patterns:
          - "*"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
  - package-ecosystem: "npm"
    directory: "/"
    groups:
      all:
        patterns:
          - "*"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/"
    groups:
      all:
        patterns:
          - "*"
    ignore:
      # DokkaとJacksonの依存関係から、2.15.3よりバージョンを上げなし
      - dependency-name: "com.fasterxml.jackson:jackson-*"
      - dependency-name: "com.fasterxml.jackson.core:jackson-*"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
