version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      all:
        patterns:
          - "*"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    groups:
      all:
        patterns:
          - "*"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/"
    groups:
      all:
        patterns:
          - "*"
    ignore:
      # DokkaとJacksonの依存関係から、2.13.5よりバージョンを上げなし
      - dependency-name: "com.fasterxml.jackson.core:jackson-databind"
    schedule:
      interval: "daily"
